# Generated by Django 5.2.16 on 2026-07-14 07:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome cantiere')),
                ('address', models.CharField(max_length=300, verbose_name='Indirizzo')),
                ('client_id', models.UUIDField(blank=True, help_text="Riferimento all'anagrafica cliente (quando esisterà).", null=True, verbose_name='ID cliente')),
                ('logo', models.ImageField(blank=True, upload_to='project_logos/', verbose_name='Logo')),
                ('tolerance_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='Tolleranza di plausibilità (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiberTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=200, verbose_name='Punto di partenza')),
                ('end_point', models.CharField(max_length=200, verbose_name='Punto di arrivo')),
                ('fiber_type', models.CharField(choices=[('sm_g652d', 'Monomodale G.652D'), ('sm_g657', 'Monomodale G.657 A/B'), ('mm_om1', 'Multimodale OM1 (62,5/125)'), ('mm_om2', 'Multimodale OM2 (50/125)'), ('mm_om3', 'Multimodale OM3 (50/125 laser-ott.)'), ('mm_om45', 'Multimodale OM4/OM5 (50/125 laser-ott.)')], max_length=20, verbose_name='Tipo di fibra')),
                ('length_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Lunghezza tratta')),
                ('length_unit', models.CharField(choices=[('km', 'km'), ('m', 'm')], default='km', max_length=2)),
                ('splice_type', models.CharField(choices=[('fusion', 'Fusione'), ('mechanical', 'Meccanica')], max_length=20, verbose_name='Tipo di giunzione')),
                ('splice_count', models.PositiveIntegerField(default=0, verbose_name='Numero giunzioni')),
                ('connector_type', models.CharField(choices=[('factory', 'Connettorizzato in fabbrica (pigtail)'), ('field', 'Terminato in campo'), ('generic', 'Generico / da capitolato')], max_length=20, verbose_name='Tipo di connettori')),
                ('connector_count', models.PositiveIntegerField(default=0, verbose_name='Numero connettori')),
                ('test_datetime', models.DateTimeField(verbose_name='Data e ora del test')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiber_tests', to='collaudi.project')),
            ],
            options={
                'ordering': ['start_point', 'end_point'],
            },
        ),
        migrations.CreateModel(
            name='FiberMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wavelength_nm', models.PositiveIntegerField(verbose_name="Lunghezza d'onda (nm)")),
                ('direction', models.CharField(choices=[('A_B', 'A → B'), ('B_A', 'B → A')], max_length=3, verbose_name='Direzione')),
                ('measured_db', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Attenuazione misurata (dB)')),
                ('fiber_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='collaudi.fibertest')),
            ],
            options={
                'ordering': ['wavelength_nm', 'direction'],
                'constraints': [models.UniqueConstraint(fields=('fiber_test', 'wavelength_nm', 'direction'), name='unique_measurement_per_test_wavelength_direction')],
            },
        ),
    ]
