# Generated by Django 5.2.16 on 2026-07-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaudi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibertest',
            name='length_unit',
            field=models.CharField(choices=[('km', 'km'), ('m', 'm')], default='km', max_length=2, verbose_name='Unità di lunghezza'),
        ),
    ]
