# Generated by Django 5.2.16 on 2026-07-15 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaudi', '0002_alter_fibertest_length_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberStrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Numero fibra')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='fibermeasurement',
            name='unique_measurement_per_test_wavelength_direction',
        ),
        migrations.AddField(
            model_name='fibertest',
            name='fiber_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Numero di fibre'),
        ),
        migrations.AddField(
            model_name='fibertest',
            name='selected_wavelengths',
            field=models.JSONField(default=list, verbose_name="Lunghezze d'onda da testare"),
        ),
        migrations.AlterField(
            model_name='fibermeasurement',
            name='fiber_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements_old', to='collaudi.fibertest'),
        ),
        migrations.AddField(
            model_name='fiberstrand',
            name='fiber_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='collaudi.fibertest'),
        ),
        migrations.AddField(
            model_name='fibermeasurement',
            name='strand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='collaudi.fiberstrand'),
        ),
        migrations.AddConstraint(
            model_name='fibermeasurement',
            constraint=models.UniqueConstraint(fields=('strand', 'wavelength_nm', 'direction'), name='unique_measurement_per_strand_wavelength_direction'),
        ),
        migrations.AlterUniqueTogether(
            name='fiberstrand',
            unique_together={('fiber_test', 'number')},
        ),
    ]
