# Generated by Django 5.2.16 on 2026-07-15 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaudi', '0004_migrate_to_strands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fibermeasurement',
            name='fiber_test',
        ),
        migrations.AlterField(
            model_name='fibermeasurement',
            name='strand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='collaudi.fiberstrand'),
        ),
    ]
