# Generated by Django 5.2.16 on 2026-07-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaudi', '0005_remove_fibermeasurement_fiber_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiberstrand',
            name='direction_mode',
            field=models.CharField(choices=[('both', 'Entrambe le direzioni'), ('a_to_b', 'Solo A → B'), ('b_to_a', 'Solo B → A')], default='both', max_length=10, verbose_name='Direzioni da testare'),
        ),
        migrations.AddField(
            model_name='fiberstrand',
            name='panel_position',
            field=models.CharField(blank=True, max_length=50, verbose_name='Posizione nel pannello'),
        ),
        migrations.AddField(
            model_name='fibertest',
            name='panel_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° pannello'),
        ),
    ]
