# Generated by Django 5.2.16 on 2026-07-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaudi', '0006_fiberstrand_direction_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiberstrand',
            name='image',
            field=models.ImageField(blank=True, upload_to='strand_images/', verbose_name='Immagine'),
        ),
    ]
