# Generated by Django 5.2.16 on 2026-07-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaudi', '0007_fiberstrand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='report_language',
            field=models.CharField(choices=[('it', 'Italiano'), ('en', 'English')], default='it', max_length=2, verbose_name='Lingua del report'),
        ),
    ]
