# Generated by Django 5.2.16 on 2026-08-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaudi', '0008_project_report_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibertest',
            name='end_position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Posizione punto di arrivo'),
        ),
        migrations.AddField(
            model_name='fibertest',
            name='start_position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Posizione punto di partenza'),
        ),
        migrations.AlterField(
            model_name='project',
            name='report_language',
            field=models.CharField(choices=[('it', 'Italiano'), ('en', 'English'), ('de', 'Deutsch')], default='it', max_length=2, verbose_name='Lingua del report'),
        ),
    ]
